// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChooseButton: typeof import('./src/components/ChooseButton.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
