// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChooseButton: typeof import('./src/components/ChooseButton.vue')['default']
    ContestBoard: typeof import('./src/components/ContestBoard.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomModal: typeof import('./src/components/CustomModal.vue')['default']
    FirsStep: typeof import('./src/components/steps/FirsStep.vue')['default']
    FirstStep: typeof import('./src/components/steps/FirstStep.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    WelcomeBoard: typeof import('./src/components/WelcomeBoard.vue')['default']
  }
}
